### ISSUE TITLE
Disables all mob collision

### ISSUE THREAD

**Issue by Dummiesman** [FunkyToc/Chairify#1]
Using this datapack disables collision with every mob. Can't push them around whatsoever.

**Comment by FunkyToc** [comment]
Thanks for report !

The team option is now : 
`team modify cf_chair collisionRule pushOwnTeam`

Download it again and use **/reload** to fix it !

**Comment by FunkyToc** [comment]
Thanks for report !

The team option is now : 
`team modify cf_chair collisionRule pushOwnTeam`

Download it again and use **/reload** to fix it !
